# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Meus Rumos
email: meusrumos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  O que vou fazer na faculdade? Será que vou fazer faculdade?
  Quais são as oportunidades que o mundo me oferece?
  Encontre o seu rumo aqui.
baseurl: "/meus-rumos" # the subpath of your site, e.g. /blog
url: "http://rafaeleiki.github.io" # the base hostname & protocol for your site
github_username:  rafaeleiki

# Build settings
markdown: kramdown
